# Don't flash in recovery!
if ! $BOOTMODE; then
    ui_print "*********************************************************"
    ui_print "! Install from recovery is NOT supported"
    ui_print "! Recovery sucks"
    ui_print "! Please install from Magisk / KernelSU / APatch app"
    abort    "*********************************************************"
fi

# Error on < Android 8
if [ "$API" -lt 26 ]; then
    abort "! You can't use this module on Android < 8.0"
fi

check_zygisk() {
    local ZYGISK_MODULE="/data/adb/modules/zygisksu"
    local REZYGISK_MODULE="/data/adb/modules/rezygisk"
    local MAGISK_DIR="/data/adb/magisk"
    local ZYGISK_MSG="Zygisk is not enabled. Please either:
    - Enable Zygisk in Magisk settings
    - Install ZygiskNext or ReZygisk module"

    # Check if Zygisk module directory exists
    if [ -d "$ZYGISK_MODULE" ] || [ -d "$REZYGISK_MODULE" ]; then
        return 0
    fi

    # If Magisk is installed, check Zygisk settings
    if [ -d "$MAGISK_DIR" ]; then
        # Query Zygisk status from Magisk database
        local ZYGISK_STATUS
        ZYGISK_STATUS=$(magisk --sqlite "SELECT value FROM settings WHERE key='zygisk';")

        # Check if Zygisk is disabled
        if [ "$ZYGISK_STATUS" = "value=0" ]; then
            abort "$ZYGISK_MSG"
        fi
    else
        abort "$ZYGISK_MSG"
    fi
}

# Module requires Zygisk to work
check_zygisk

# safetynet-fix module is obsolete and it's incompatible with PIF
SNFix="/data/adb/modules/safetynet-fix"
if [ -d "$SNFix" ]; then
    ui_print "! safetynet-fix module is obsolete and it's incompatible with PIF, it will be removed on next reboot"
    ui_print "! Do not install it"
    touch "$SNFix"/remove
fi

# playcurl warn
if [ -d "/data/adb/modules/playcurl" ]; then
    ui_print "! playcurl may overwrite fingerprint with invalid one, be careful!"
fi

# MagiskHidePropsConf module is obsolete in Android 8+ but it shouldn't give issues
if [ -d "/data/adb/modules/MagiskHidePropsConf" ]; then
    ui_print "! WARNING, MagiskHidePropsConf module may cause issues with PIF."
fi

# Preserve previous setting
spoofConfig="spoofProvider spoofProps spoofSignature DEBUG spoofVendingSdk"
for config in $spoofConfig; do
    grep -q "$config" "/data/adb/modules/playintegrityfix/pif.json" || continue
    if grep -q "\"$config\": true" "/data/adb/modules/playintegrityfix/pif.json"; then
        sed -i "s/\"$config\": .*/\"$config\": true,/" "$MODPATH/pif.json"
    else
        sed -i "s/\"$config\": .*/\"$config\": false,/" "$MODPATH/pif.json"
    fi
done
sed -i ':a;N;$!ba;s/,\n}/\n}/g' "$MODPATH/pif.json"

# Preserve cron configuration from previous installation
if [ -f "/data/adb/modules/playintegrityfix/cron_config" ]; then
    ui_print "- Preserving cron configuration"
    cp -f "/data/adb/modules/playintegrityfix/cron_config" "$MODPATH/cron_config"
fi

# Check custom fingerprint
if [ -f "/data/adb/pif.json" ]; then
    ui_print "- Backup custom pif.json"
    mv -f /data/adb/pif.json /data/adb/pif.json.old
fi

# Create necessary directories for cron functionality
# Handle existing backup directory during module updates
if [ -d "$MODPATH/backup" ]; then
    # Backup directory already exists, preserve user preferences but clean up runtime files
    ui_print "- Cleaning up previous cron runtime files"
    # Keep user preference files like 'nowakelock' but remove runtime files
    # Runtime files: cron_pid (process ID), root (busybox cron config)
    # These will be regenerated when cron service starts
    rm -f "$MODPATH/backup/cron_pid" "$MODPATH/backup/root" 2>/dev/null || true
else
    # Create new backup directory for fresh installation
    mkdir -p "$MODPATH/backup"
fi

# Preserve existing backup directory from previous installation (for module updates)
if [ -d "/data/adb/modules/playintegrityfix/backup" ] && [ "$MODPATH" != "/data/adb/modules/playintegrityfix" ]; then
    ui_print "- Preserving backup directory from previous installation"
    # Copy user preference files but not runtime files
    if [ -f "/data/adb/modules/playintegrityfix/backup/nowakelock" ]; then
        cp -f "/data/adb/modules/playintegrityfix/backup/nowakelock" "$MODPATH/backup/"
        ui_print "  - Preserved wake lock disable setting"
    fi
    # Note: We intentionally don't copy cron_pid and root files as they are runtime-specific
    # and will be regenerated by the cron manager when the service starts
fi

# give exec perm to action.sh and cron_manager.sh
chmod +x "$MODPATH/action.sh"
chmod +x "$MODPATH/cron_manager.sh"

